spring:
  application:
    name: hotelManager

  jpa:
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/hotel
    username: postgres
    password: postgres


server:
  port: 8081
  servlet:
    context-path: api/v1